name: Deploy Frontend to VPS

on:
  push:
    branches:
      - integrazione

jobs:
  deploy:
    name: Deploy FE
    runs-on: self-hosted

    steps:
      - name: Pull latest code and rebuild frontend
        run: |
          cd /opt/stacks/sito-banda/sito-presentazione-banda-fe-new
          git pull origin integrazione
          cd /opt/stacks/sito-banda
          docker compose up --build -d frontend
          echo "✅ FE Deploy completato"
